baseURL = "https://ocss.nz/"
title = "Otago Computing Students Society"
theme = "hello-friend-ng"

languageCode = "en-NZ"
timeZone = "Pacific/Auckland"

sectionPagesMenu = "main"

copyright = "All Rights Reserved"

[markup.goldmark.renderer]
    unsafe = true

[params]
    customCSS = ["/css/footer-logo.css"]
    customJS  = []

    enableThemeToggle = true
    enableSharingButtons = true

    titleSeparator = "|"

#    description = ""
#    homeSubtitle = ""
#    keywords = ""
#    images = [""]

    [params.author]
        name = "Otago Computing Students Society"

    [params.logo]
#        path = "/images/logo.svg"
#        logoMark = "$"
        logoText = "cd /home/ocss"
        logoCursorPathname = false
        logoCursorDisabled = true

    [params.portrait]
        path = "/images/logo.svg"
        alt = "OCSS Logo"
        circle = false
        maxWidth = "50%"

    [params.footer]
        socials = true

        trademark = 2023
        author = true
        copyright = true
#        rss = true

        topText = []
        bottomText = ["Powered by: [<img src=\"/images/cloudcannon-logo.svg\" alt=\"CloudCannon\" class=\"footer-logo\">](https://cloudcannon.com/)"]

    [[params.social]]
        name = "ousa"
        url  = "https://www.ousa.org.nz/clubsandsocs/clubs/clubs-list/otago-computing-students-society"

    [[params.social]]
        name = "email"
        url  = "mailto:contact@ocss.nz"

    [[params.social]]
        name = "github"
        url  = "https://github.com/Otago-Computing-Students-Society"

    [[params.social]]
        name = "facebook"
        url  = "https://www.facebook.com/OtagoCSS"

    [[params.social]]
        name = "instagram"
        url  = "https://www.instagram.com/otagocss/"

    [[params.social]]
        name = "tiktok"
        url  = "https://www.tiktok.com/@otago.css"

    [[params.social]]
        name = "youtube"
        url = "https://www.youtube.com/@OtagoCSS"

    [[params.social]]
        name = "linkedin"
        url  = "https://nz.linkedin.com/company/otago-computing-students-society"

    [[params.social]]
        name = "discord"
        url  = "https://discord.com/invite/bpmFsDbprD"
