baseURL = "https://ocss.nz/"
title = "Otago Computing Students Society"
theme = "hello-friend-ng"

languageCode = "en-NZ"
timeZone = "Pacific/Auckland"

sectionPagesMenu = "main"

[params]
    enableThemeToggle = true
    enableSharingButtons = true

    [params.author]
        name = "Otago Computing Students Society"

    [params.logo]
#        path = "/images/logo.svg"
        logoMark = ">"
        logoText = "$ cd /home/"
        logoCursorPathname = true
        logoCursorDisabled = true

    [params.portrait]
        path = "/images/logo.svg"
        alt = "OCSS Logo"
        circle = false

    [params.footer]
        socials = true
#        trademark = 2023
#        rss = true
#        copyright = true
#        author = true

        topText = []
        bottomText = []

    [[params.social]]
        name = "email"
        url  = "mailto:contact@ocss.nz"

    [[params.social]]
        name = "github"
        url  = "https://github.com/Otago-Computing-Students-Society"

    [[params.social]]
        name = "facebook"
        url  = "https://www.facebook.com/OtagoCSS"

    [[params.social]]
        name = "instagram"
        url  = "https://www.instagram.com/otagocss/"

    [[params.social]]
        name = "tiktok"
        url  = "https://www.tiktok.com/@otago.css"

    [[params.social]]
        name = "linkedin"
        url  = "https://nz.linkedin.com/company/otago-computing-students-society"

    [[params.social]]
        name = "discord"
        url  = "https://discord.com/invite/bpmFsDbprD"

#    [[params.social]]
#        name = "ousa-clubs"
#        url  = "https://www.ousa.org.nz/clubsandsocs/clubs/clubs-list/otago-computing-students-society"
